### Create a new Report

POST http://localhost:3000/reports
content-type: application/json

{
  "price": 10,
  "make": "Toyota",
  "model": "corrolla",
  "mileage": 20000,
  "lng": 0,
  "lat": 34,
  "year": 2020
}
